---
title: "Comparing_Data_Frames"
author: "Barry DeCicco"
format: html
editor: visual
---


# This file uses the comparedf() function to compare two data frames:

This function is in the package **arsenal**.

```{r}
#| label: load-packages

library(tidyverse)
library(magrittr)
library(ggplot2)
library(janitor)
# library(difdf)
library(vetr)
library(knitr)
library(quarto)
library(compareDF)
library(arsenal)


```
Create two data frames, slightly different:


```{r}
#| label: create-data-frames

df1 <- data.frame(id = paste0("person", 1:3),
                  a = c("a", "b", "c"),
                  b = c(1, 3, 4),
                  c = c("f", "e", "d"),
                  row.names = paste0("rn", 1:3),
                  stringsAsFactors = FALSE)
df2 <- data.frame(id = paste0("person", 3:1),
                  a = c("c", "b", "a"),
                  b = c(1, 3, 4),
                  d = paste0("rn", 1:3),
                  row.names = paste0("rn", c(1,3,2)),
                  stringsAsFactors = FALSE)



```

Run the comparedf function:

```{r}

#| label: run-comparedf-function

comparison1 <- comparedf(df1, df2)


```

Print the comparedf object:


```{r}
#| label: print-comparison

comparison1

```

```{r}
#| label: summary-comparison

summary(comparison1)

```
